# Modelo Machine Learning



El modelo de la similitud del coseno funciona comparando vectores, los cuales obtenemos de nuestros datasets, los vectores son comparados en un espacio en el que se evalua el valor del coseno comprendido entre ellos.

In [1]:
import pandas as pd 
from sklearn.metrics.pairwise import cosine_similarity


**Leer frame para el modelo:**

In [2]:
item_model= pd.read_csv('Frame_ML.csv', low_memory=False) 


In [3]:
item_model.head(3) 

user_id                                       genres  \
0  76561197970982479      Action Casual Indie Simulation Strategy   
1  76561197970982479              Free to Play Indie RPG Strategy   
2  76561197970982479  Casual Free to Play Indie Simulation Sports   

                app_name   item_id  
0    Lost Summoner Kitty  761140.0  
1              Ironbound  643980.0  
2  Real Pool D  Poolians  670290.0

**Crear un dataframe que contenga las columnas de generos**

In [4]:
# Creación de dummies
item_model = pd.get_dummies(item_model, columns=['genres'], prefix="")

# Agrupación por 'user_id' e 'item_id', sumando las columnas
item_model = item_model.groupby(['item_id','app_name']).sum().reset_index()

item_model.head(3)

item_id               app_name    user_id  _Action  _Action Adventure  \
0     10.0          CounterStrike  relesprit        1                  0   
1     20.0  Team Fortress Classic  relesprit        1                  0   
2     30.0          Day of Defeat  relesprit        1                  0   

   _Action Adventure Casual  _Action Adventure Casual Free to Play Indie  \
0                         0                                            0   
1                         0                                            0   
2                         0                                            0   

   _Action Adventure Casual Free to Play Indie Early Access  \
0                                                  0          
1                                                  0          
2                                                  0          

   _Action Adventure Casual Free to Play Indie Massively Multiplayer  \
0                                                  0                   
1                                                  0                   
2                                                  0                   

   _Action Adventure Casual Free to Play Indie Massively Multiplayer RPG Early Access  \
0                                                  0                                    
1                                                  0                                    
2                                                  0                                    

   ...  _Strategy Indie Simulation  _Strategy RPG  _Strategy RPG Indie  \
0  ...                           0              0                    0   
1  ...                           0              0                    0   
2  ...                           0              0                    0   

   _Strategy Simulation  _Utilities  _Utilities Early Access  \
0                     0           0                        0   
1                     0           0                        0   
2                     0           0                        0   

   _Utilities Video Production  _Utilities Video Production Early Access  \
0                            0                                         0   
1                            0                                         0   
2                            0                                         0   

   _Utilities Web Publishing  _Web Publishing  
0                          0                0  
1                          0                0  
2                          0                0  

[3 rows x 806 columns]

In [5]:
coseno_similit = cosine_similarity(item_model.iloc[:,3:])

C:\Users\alexi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\extmath.py:192: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b


In [6]:
print(coseno_similit)

[[1. 1. 1. ... 1. 0. 1.]
 [1. 1. 1. ... 1. 0. 1.]
 [1. 1. 1. ... 1. 0. 1.]
 ...
 [1. 1. 1. ... 1. 0. 1.]
 [0. 0. 0. ... 0. 1. 0.]
 [1. 1. 1. ... 1. 0. 1.]]


**Función de recomendación de juegos**

In [7]:
def recomendacion_juegos(item_id):
    item_id = int(item_id)
    
    # Aqui lo que hare es como igualarlo comforme al id del juego.
    seleccion_juego = item_model[item_model['item_id'] == item_id]
    
    # Devolver error en caso de vacío
    if seleccion_juego.empty:
        return "El juego con el item especificado no existe en la base de datos."
    
    # Calcula la similitud del juego que se ingresa con otros juegos del dataframe
    similarity_scores = coseno_similit[item_model[item_model['item_id'] == item_id].index[0]]
    
    # Calcula los índices de los juegos más similares (excluyendo el juego de entrada)
    juegos_similares = similarity_scores.argsort()[::-1][1:6]
    
    # Obtener los nombres de los juegos 5 recomendados
    juegos_recomendados = item_model.iloc[juegos_similares]['app_name']
    
    return list(juegos_recomendados)


In [8]:
recomendados = recomendacion_juegos(280)
recomendados

['Heavy Fire Shattered Spear',
 'Necromonads',
 'Circuit Breakers',
 'Umbrella CorpsBiohazard Umbrella Corps',
 'Mushihimesama OST']

Dividir el dataframe para a render

In [9]:
#Cuento filas
filas= len(item_model)

#Calculo la mitad
mitad_filas= filas // 10
 
#Selecciono la mitad superior
render_model= item_model.iloc[:mitad_filas]

In [10]:
coseno_render = cosine_similarity(item_model.iloc[:,3:])

C:\Users\alexi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\extmath.py:192: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b


In [11]:
render_model.to_csv('Model_render.csv',index=False)

In [12]:
render_model.head()

item_id                 app_name    user_id  _Action  _Action Adventure  \
0     10.0            CounterStrike  relesprit        1                  0   
1     20.0    Team Fortress Classic  relesprit        1                  0   
2     30.0            Day of Defeat  relesprit        1                  0   
3     40.0       Deathmatch Classic  relesprit        1                  0   
4     50.0  HalfLife Opposing Force  relesprit        1                  0   

   _Action Adventure Casual  _Action Adventure Casual Free to Play Indie  \
0                         0                                            0   
1                         0                                            0   
2                         0                                            0   
3                         0                                            0   
4                         0                                            0   

   _Action Adventure Casual Free to Play Indie Early Access  \
0                                                  0          
1                                                  0          
2                                                  0          
3                                                  0          
4                                                  0          

   _Action Adventure Casual Free to Play Indie Massively Multiplayer  \
0                                                  0                   
1                                                  0                   
2                                                  0                   
3                                                  0                   
4                                                  0                   

   _Action Adventure Casual Free to Play Indie Massively Multiplayer RPG Early Access  \
0                                                  0                                    
1                                                  0                                    
2                                                  0                                    
3                                                  0                                    
4                                                  0                                    

   ...  _Strategy Indie Simulation  _Strategy RPG  _Strategy RPG Indie  \
0  ...                           0              0                    0   
1  ...                           0              0                    0   
2  ...                           0              0                    0   
3  ...                           0              0                    0   
4  ...                           0              0                    0   

   _Strategy Simulation  _Utilities  _Utilities Early Access  \
0                     0           0                        0   
1                     0           0                        0   
2                     0           0                        0   
3                     0           0                        0   
4                     0           0                        0   

   _Utilities Video Production  _Utilities Video Production Early Access  \
0                            0                                         0   
1                            0                                         0   
2                            0                                         0   
3                            0                                         0   
4                            0                                         0   

   _Utilities Web Publishing  _Web Publishing  
0                          0                0  
1                          0                0  
2                          0                0  
3                          0                0  
4                          0                0  

[5 rows x 806 columns]

Función item-item

In [13]:
def encontrar_juegos(item_id):
    # Encuentra el índice del juego ingresado por item_id
    juego_indice = render_model.index[render_model['item_id'] == item_id].tolist()[0]
    
    # Extraigo las características del juego 
    juego_caracteristicas = render_model.iloc[juego_indice, 3:].values.reshape(1, -1)
    
    # Y acá se calcula la similitud coseno entre el juego ingresado y todos los demás juegos
    render = cosine_similarity(render_model.iloc[:, 3:], juego_caracteristicas)
    
    # Obtiene los índices de los juegos más similares (excluyendo el juego de entrada)
    lineas_juegos_similares = render.argsort(axis=0)[::-1][1:6]
    lineas_juegos_similares = lineas_juegos_similares.flatten()[1:]
    
    # Obtiene los juegos más similares en función de los índices
    juegos_similares = render_model.iloc[lineas_juegos_similares]['app_name']
    
    return juegos_similares

In [14]:
juegos_similares = encontrar_juegos(10)
print(juegos_similares)

1047                               Call of Duty Black Ops
1046    Call of Duty Modern Warfare  Collection  Final...
1045    Call of Duty Modern Warfare  Collection  Chaos...
1044             Call of Duty Modern Warfare  Collection 
Name: app_name, dtype: object
